import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../../../globals.css';
import Sidebar from './_components/sidebar';
import Header from './_components/header';
import { redirect } from 'next/navigation';
import { getUser } from '@/lib/auth';

const geistSans = localFont({
  src: '../../../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../../../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { session } = await getUser();
  if (!session) {
    redirect('/dashboard/sign-in');
  }
  return (
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div className='flex min-h-screen w-full flex-col bg-muted/40'>
        <Sidebar />
        <div className='flex flex-col sm:gap-4 sm:py-4 sm:pl-14'>
          <Header />
          <main className='py-4 px-6'>{children}</main>
        </div>
      </div>
    </body>
  );
}
